# Generated by Django 3.1.4 on 2021-02-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='obj',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
