# Generated by Django 3.1.4 on 2021-02-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_obj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='obj',
        ),
    ]
