# Generated by Django 3.1.4 on 2021-02-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210201_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='limit',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=1),
            preserve_default=False,
        ),
    ]
