# Generated by Django 3.1.4 on 2021-02-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysis_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='topic',
            field=models.CharField(max_length=300),
        ),
    ]
