# Generated by Django 3.1.4 on 2021-02-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20210201_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='limit',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Top Posts to be searched in Reddit'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='topic',
            field=models.CharField(max_length=300, verbose_name='Topic to be searched in Reddit'),
        ),
    ]
