# Generated by Django 3.1.4 on 2021-02-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20210201_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='time_filter',
            field=models.CharField(choices=[('all', 'all'), ('day', 'day'), ('hour', 'hour'), ('month', 'month'), ('week', 'week'), ('year', 'year')], default='all', max_length=300, verbose_name='Reddit API time interval'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='limit',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Count of "Top Posts" to be searched in Reddit.Default value=all'),
        ),
    ]
