# Generated by Django 3.1.4 on 2021-02-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20210201_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='limit',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (20, 20), (50, 50), (100, 100)], verbose_name='Count of "Top Posts" to be searched in Reddit.Default value=all'),
        ),
    ]
