# Generated by Django 3.1.4 on 2021-02-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20210202_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='limit',
            field=models.IntegerField(default=1, verbose_name='Count of "Top Posts" to be searched in Reddit.'),
            preserve_default=False,
        ),
    ]
