# Generated by Django 3.1.4 on 2021-02-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_analysis_word_cloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='word_cloud',
        ),
    ]
